EXPLAIN SELECT * FROM READERS WHERE FIRSTNAME = 'John';

CREATE INDEX idx_readers_name ON READERS(FIRSTNAME, LASTNAME);
CREATE INDEX idx_books_title ON BOOKS(TITLE);

EXPLAIN SELECT * FROM READERS WHERE FIRSTNAME = 'John';