CREATE TABLE STATS (
                       STAT_ID INT(11) AUTO_INCREMENT PRIMARY KEY,
                       STAT_DATE DATETIME NOT NULL,
                       STAT VARCHAR(20) NOT NULL,
                       VALUE INT(11) NOT NULL
);

CREATE VIEW BESTSELLERS_COUNT AS
SELECT COUNT(*) AS bestseller_count
FROM BOOKS
WHERE BESTSELLER = 1;

DELIMITER $$

CREATE EVENT UPDATE_BESTSELLERS
ON SCHEDULE EVERY 1 MINUTE
DO
BEGIN

INSERT INTO STATS (STAT_DATE, STAT, VALUE)
SELECT NOW(),'BESTSELLERS', bestseller_count
FROM BESTSELLERS_COUNT;
END $$

DELIMITER ;

SHOW PROCESSLIST;

SELECT * FROM STATS;

DROP EVENT UPDATE_BESTSELLERS;